### ISSUE TITLE
PopulationScreening Communication: "Subject" has to be mandatory

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#51]
Is it possible to make the subject field mandatory because we link the SSIN to a common Patient ("basic" resource) based on the subject field?
![PopulationScreening Communication_subject](https://github.com/hl7-be/public-health/assets/113599686/5291d0b8-adae-414e-8bd1-11ff823b4523)

**Comment by costateixeira** [comment]
I think that makes sense, yes.

**Comment by vmichie** [comment]
Vitalink discussed this with the business and the technical team and both agreed to the requested change.

**Comment by bdc-ehealth** [comment]
@vmichie ,

Was this a WG decision? If the consensus in the WG was by mail, can I have a copy of it, so that I can add this decision to this issue?

**Comment by vmichie** [comment]
> @vmichie ,
> 
> Was this a WG decision? If the consensus in the WG was by mail, can I have a copy of it, so that I can add this decision to this issue?

@bdc-ehealth : I have sent you the communication by e-mail.

**Comment by bdc-ehealth** [comment]
according to @vmichie all members of the WG have discussed this by email. I paste the discussion below:

Dag Bart,

Heb je voldoende referenties opdat issue PopulationScreening Communication: "Subject" has to be mandatory · Issue #51 · hl7-be/public-health · GitHub kan opgelost worden?

Met vriendelijke groeten, 
 
Veerle Michiels 
Analist 
 
DEPARTEMENT ZORG 
Afdeling Communicatie en IT 
T 02 553 25 75
veerle.michiels@***

BEZOEKADRES
Koning Albert II-laan 35, 1030 Brussel
*Op 29 april 2024 verhuizen we naar: Belpairegebouw, Simon Bolivarlaan 17, 1000 Brussel
Stuur uw briefwisseling vanaf 4 maart 2024 naar:
Koning Albert II-laan 15 bus 495, 1210 Brussel
www.departementzorg.be 
 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
 
  
 

________________________________________
Van: Michiels Veerle ***@***
Verzonden: donderdag 28 maart 2024 11:40
Aan: Bart.Decuypere@*** ***@***
Onderwerp: Subject" has to be mandatory
 
Dag Bart,

Om issue https://github.com/hl7-be/public-health/issues/51 te kunnen oplossen hierbij het mailverkeer tussen de deelnemers van de WG. 
Sophie Van der Fraenen maakt deel uit van het technisch team van CvKO (PopulationScreening) en Maxime Caucheteur maakt deel uit van het Smals FHIR team, het team van Vitalink. 
 
PopulationScreening Communication: "Subject" has to be mandatory · Issue #51 · hl7-be/public-health
Is it possible to make the subject field mandatory because we link the SSIN to a common Patient ("basic" resource) based on the subject field?
github.com


Met vriendelijke groeten, 
 
Veerle Michiels 
Analist 
 
DEPARTEMENT ZORG 
Afdeling Communicatie en IT 
T 02 553 25 75
veerle.michiels@***
BEZOEKADRES
Koning Albert II-laan 35, 1030 Brussel
*Op 29 april 2024 verhuizen we naar: Belpairegebouw, Simon Bolivarlaan 17, 1000 Brussel
Stuur uw briefwisseling vanaf 4 maart 2024 naar:
Koning Albert II-laan 15 bus 495, 1210 Brussel
www.departementzorg.be 
 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
 
  
 

________________________________________
Van: maxime.caucheteur@smals.be ***@***
Verzonden: vrijdag 19 januari 2024 10:54
Aan: Michiels Veerle ***@***
CC: Brecht Van Vooren (Smals) ***@***
Onderwerp: RE: Statusupdate CvKO FHIR-a-thon
 
Hi Veerle,
 
The reason this error occurs is because the Communication resource needs to contain the “subject” field with the patient pseudonymized ssin (I updated the JSON, see attachment).
 
We need this field in the resource because we are linking the identifier to a “basic” resource based on the “subject” field.
 
Best regards,
Maxime Caucheteur
 
From: Michiels Veerle ***@***
Sent: 19 January 2024 10:17
To: Brecht Van Vooren (SMALS) ***@***; Maxime Caucheteur (SMALS) ***@***
Subject: FW: Statusupdate CvKO FHIR-a-thon
 
Hi Brecht and Maxime,
Could you have a look to the respons that I got from Axians?
 
Met vriendelijke groeten
 
Veerle Michiels
Analist
 
DEPARTEMENT ZORG
Afdeling Communicatie en IT
T 02 553 25 75
Bel mij via teams
Stuur mij een chatbericht in teams
veerle.michiels@***
Koning Albert II-laan 35 bus 33, 1030 Brussel
www.departementzorg.be
 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
 
 
 
Op 1 juni 2023 fuseerden het Departement Welzijn, Volksgezondheid en Gezin en het Agentschap Zorg en Gezondheid tot
het nieuwe Departement Zorg.
 
Van: VAN DER FRAENEN Sophie ***@***
Verzonden: vrijdag 19 januari 2024 10:14
Aan: Michiels Veerle ***@***
CC: GEIRREGAT Thijs ***@***; DHAENE Kurt ***@***
Onderwerp: Re: Statusupdate CvKO FHIR-a-thon
 
	Wees alert! Heeft u twijfels over waarom u dit bericht ontvangt of kent u de afzender niet, open geen bijlages, klik niet op links en contacteer servicedesk @ vlaanderen . be indien u ondersteuning noodzakelijk acht.
 
Dag Veerle,
 
We hebben opnieuw getest, maar geen succes. Dit is de foutmelding die we nu krijgen:

 
 
We hebben getest met de bundle uit de eerste mail, en met een nieuwe bundle die je als bijlage in deze mail terug kan vinden. Deze tweede bundle is wat eenvoudiger en bevat enkel een careplan en een commication. (Beide bundles vind je ook terug in de zip met json voorbeelden die Kurt reeds heeft aangeleverd).
 
De foutmelding is ons niet geheel duidelijk aangezien we wel een patient identifier in de bundje hebben, met het gepseudonimiseerd rijksregisternummer.
 
 
Met vriendelijke groeten,
Cordialement,
Kind regards,
 
Sophie Van der Fraenen
 
 
 
 
 
Verlorenbroodstraat 122 – 9820 Merelbeke
 
________________________________________
Van: Michiels Veerle ***@***
Verzonden: vrijdag 19 januari 2024 08:07
Aan: DHAENE Kurt ***@***; VAN DER FRAENEN Sophie ***@***
CC: GEIRREGAT Thijs ***@***
Onderwerp: FW: Statusupdate CvKO FHIR-a-thon
 
Beste,
Zouden jullie opnieuw willen testen?
De aanpassing werden uitgevoerd aan onze kant.
 
Met vriendelijke groeten
 
Veerle Michiels
Analist
 
DEPARTEMENT ZORG
Afdeling Communicatie en IT
T 02 553 25 75
Bel mij via teams
Stuur mij een chatbericht in teams
veerle.michiels@vlaanderen.be
Koning Albert II-laan 35 bus 33, 1030 Brussel
www.departementzorg.be
 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
 
 
 
Op 1 juni 2023 fuseerden het Departement Welzijn, Volksgezondheid en Gezin en het Agentschap Zorg en Gezondheid tot
het nieuwe Departement Zorg.
 
Van: Michiels Veerle
Verzonden: vrijdag 19 januari 2024 7:53
Aan: GEIRREGAT Thijs ***@***
Onderwerp: RE: Statusupdate CvKO FHIR-a-thon
 
Dag Thijs
 
Vandaag wordt er een nieuwe versie van onze configuratietool gedeployed waarna jullie opnieuw kunnen testen
De aanpassing komt door het feit dat Heracles FHIR Vitalink FHIR wenst te aan te spreken als “organizations” en deze userProfile zal vandaag beschikbaar komen.
 
 
"clientId": "cbe-0870354868",
"userProfile": {
    "organizations": [
      {
        "enterprise": {
          "cbe": "0870354868"
        },
        "name": "Centrum voor Kankeropsporing"
      }
    ]
  }
 
Ik hou je op de hoogte als de nieuwe versie beschikbaar is.
 
Met vriendelijke groeten
 
Veerle Michiels
Analist
 
DEPARTEMENT ZORG
Afdeling Communicatie en IT
T 02 553 25 75
Bel mij via teams
Stuur mij een chatbericht in teams
veerle.michiels@***
Koning Albert II-laan 35 bus 33, 1030 Brussel
www.departementzorg.be
 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
 
 
 
Op 1 juni 2023 fuseerden het Departement Welzijn, Volksgezondheid en Gezin en het Agentschap Zorg en Gezondheid tot
het nieuwe Departement Zorg.
 
Van: GEIRREGAT Thijs ***@***
Verzonden: donderdag 18 januari 2024 17:46
Aan: Michiels Veerle ***@***
Onderwerp: RE: Statusupdate CvKO FHIR-a-thon
 
	Wees alert! Heeft u twijfels over waarom u dit bericht ontvangt of kent u de afzender niet, open geen bijlages, klik niet op links en contacteer servicedesk @ vlaanderen . be indien u ondersteuning noodzakelijk acht.
 
Dag Veerle,
 
Heb je al een update gehad van het technisch team?
 
Met vriendelijke groet,
Kind regards,
 
Thijs Geirregat
 
 
 
 	
 
 
Sluispark – Verlorenbroodstraat 122 - 9820 Merelbeke
thijs.geirregat@***
www.axians.be
 
From: Michiels Veerle ***@***
Sent: Monday, January 15, 2024 11:50 AM
To: VAN DER FRAENEN Sophie ***@***
Cc: GEIRREGAT Thijs ***@***; Longin Stijn ***@***; DHAENE Kurt ***@***; Leclercq Dominiek ***@***
Subject: RE: Statusupdate CvKO FHIR-a-thon
 
Dag Sophie
 
Onderstaande feedback werd deze ochtend al aan ons technisch team bezorgd, ik plan een teamsmeeting in van zodra ik meer informatie ontvangen heb.
 
Met vriendelijke groeten
 
Veerle Michiels
Analist
 
DEPARTEMENT ZORG
Afdeling Communicatie en IT
T 02 553 25 75
Bel mij via teams
Stuur mij een chatbericht in teams
veerle.michiels@***
Koning Albert II-laan 35 bus 33, 1030 Brussel
www.departementzorg.be
 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
 
 
 
Op 1 juni 2023 fuseerden het Departement Welzijn, Volksgezondheid en Gezin en het Agentschap Zorg en Gezondheid tot
het nieuwe Departement Zorg.
 
Van: VAN DER FRAENEN Sophie ***@***
Verzonden: vrijdag 12 januari 2024 18:41
Aan: Michiels Veerle ***@***; Leclercq Dominiek ***@***
CC: GEIRREGAT Thijs ***@***; Longin Stijn ***@***; DHAENE Kurt ***@***
Onderwerp: Statusupdate CvKO FHIR-a-thon
 
	Wees alert! Heeft u twijfels over waarom u dit bericht ontvangt of kent u de afzender niet, open geen bijlages, klik niet op links en contacteer servicedesk @ vlaanderen . be indien u ondersteuning noodzakelijk acht.
 
Dag iedereen,
 
Om deze week goed te eindigen, even een korte status update.
 
•	Sinds gisteren, 11 januari, kunnen we bij ehealth onze token ophalen. Een voorbeeldtoken werd reeds doorgemaild, zoals gevraagd op de statusmeeting van 8 januari.
 
•	Met deze token kunnen we ondertussen ook succesvol een rijksregisternummer pseudonimiseren!
 
•	De laatste stap in de schakel is de fhir resources, met het pseudoniem, doorsturen naar vitalink. Deze stap verloopt nog niet helemaal goed. Daarom lijkt het mij nuttig om eens samen te zitten zodat we in de loop van volgende week  data naar vitalink kunnen sturen.
Samengevat denk ik dat we succesvol binnen geraken in vitalink, maar dat er verder nog iets misloopt. Dit lijkt me een probleem waar we op dit moment vanuit Axians niet veel aan kunnen doen. Ik licht het probleem hieronder al even kort toe, zodat de info direct kan doorgestuurd worden naar de nodige mensen.
@veerle.michiels@*** kan jij met onderstaande info verder? Indien er een aanpassing nodig is aan onze json, hoor ik het graag. Direct een teams-call opzetten is dan misschien nog het snelst, dan kunnen we onmiddellijk testen. Langs onze kant mag je Kurt en mijzelf uitnodigen.  Enkel maandag van 11u-12u kan ik niet. De rest is nog vrij. 
 
 
Waar loop het nog mis:
Bij beide testen maakten we gebruik van de FHIR transaction bundle die jullie in bijlage kunnen terugvinden. Deze bundle bevat al een pseudoniem en dus niet het rijksregisternummer!
 
1.	Tijdens testen met swagger
o	De swagger link die in het vitalink cookbook v0.3 wordt vermeld (https://apps-acpt.vitalink-services.be/vault/api/r4/swagger-ui/) werkt niet. Dus hiermee konden we helaas niet testen. Eerder deze week ontvingen we wel een draft cookbook met volgende swagger url: https://vitalink-fhir-vault.acc.pub.vascloud.be/api/r4/swagger-ui/ . Het is met deze laatste swagger dat we in volgende stappen hebben gewerkt. We maken gebruik van de POST call voor de FHIR transaction bundle.
	 
o	De request body is de json die je in bijlage terugvindt. Bij authorisatie maken we gebruik van de optie 'bearerAuth', waarin we onze ehealth token plaatsen.
o	De response hier is: 
	 
 
2.	 
3.	Tijdens testen met onze eigen applicatie
o	We sturen de bundle door naar volgende url: https://apps-acpt.vitalink-services.be/vault/api/r4 . Deze url komt uit het vitalink cookbook v0.3
o	Het antwoord op deze call is hetzelfde als bij de swagger testen:
	'ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 : HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.rest.api.RestOperationTypeEnum.name()" because the return value of "be.smals.departementzorg.vitalink_fhir.vault.common.events.VitalinkEvent.getAdditionalInformation(String)" is null'.
4.	 
 
Goed weekend iedereen!
 
 
Met vriendelijke groeten,
Cordialement,
Kind regards,
 
Sophie Van der Fraenen
 
 
 
 
 
Verlorenbroodstraat 122 – 9820 Merelbeke
 

________________________________________
Overeenkomstig de bepalingen inzake de vertegenwoordiging van de vzw in haar statuten, kan enkel de gedelegeerde bestuurder, de algemeen directeur of zijn uitdrukkelijke lasthebber verbintenissen aangaan namens Smals.
Indien dit bericht niet voor u bestemd is, verzoeken wij u dit onmiddellijk aan ons te melden en het bericht te vernietigen.

Conformément aux dispositions relatives à la représentation de l'asbl dans ses statuts, seul l'administrateur délégué, le directeur général ou son mandataire exprès est habilité à souscrire des engagements au nom de Smals.
Si ce message ne vous est pas destiné, nous vous prions de nous le signaler immédiatement et de détruire le message.

According to the provisions regarding representation of the non profit association in its bylaws, only the chief executive officer, the general manager or his explicit agent can enter into engagements on behalf of Smals.
If you are not the addressee of this message, we kindly ask you to signal this to us immediately and to delete the message.
