### ISSUE TITLE
Addendum issue #50 use of "END" in the profile Population Screening Appointment

### ISSUE THREAD

**Issue by vmichie** [hl7-be/public-health#55]
Hi,
I would like to note that resource profile Population Screening Appointment had to use "END" because it is technical required. **Is it possible to add a comment that the use of END functionally requested but does not apply to the use cases of population screening?** 
Source: https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition-be-populationscreening-appointment-definitions.html#Appointment
![Population Screening Appointment - Definitions - HL7 FHIR Implementation Guide_ ](https://github.com/hl7-be/public-health/assets/113599686/51117f77-7349-49ea-890a-fd8f074258c7)

**Comment by bdc-ehealth** [comment]
@vmichie Can you take a look whether this suits your needs? https://build.fhir.org/ig/hl7-be/public-health/StructureDefinition-be-populationscreening-appointment.html

**Comment by vmichie** [comment]
Hi @bdc-ehealth , is it possible to make a change because the start and end date are the same, not "may be" the same because when you fill in the start date, you must fill in the end date. 
@kridhaen : are you agree that we should made the start date mandatory because we have always a start date of the screening periode?

**Comment by kridhaen** [comment]
@vmichie Currently we always provide a start date. In that sense, it may be made mandatory.

**Comment by bdc-ehealth** [comment]
@kridhaen @vmichie @PBACIN @HanneVuegen

Since we are doing a cardinality change here ( 9dd2521 ) : https://github.com/hl7-be/public-health/issues/55#issuecomment-2100160581 , I would like to have the confirmation of a "virtual" HL7 Workgroup Public-Health to merge this to the master branch.

You can check the result here: https://build.fhir.org/ig/hl7-be/public-health/branches/issue-55/StructureDefinition-be-populationscreening-appointment.html

**Comment by bdc-ehealth** [comment]
Votes were recorded in https://be-ehealth-standards.atlassian.net/jira/servicedesk/projects/ESI/queues/custom/19/ESI-764 , the outcome is positive.
