### ISSUE TITLE
Logical Model: nextInvitationIndication Appointment?

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#8]

**Comment by bdc-ehealth** [comment]
WG: Project team: can you ask whether this is a limited list of values. If this is the case, maybe this is a good candidate for a CodeableConcept.

**Comment by bdc-ehealth** [comment]
WG: Appointment doesn't seem to fit, because the date should be complete, and not an indication of a date.

The list of reasons can be made, but there should be an indication of a date possible.

Change the logical model to contain a code + a partial date.

**Comment by costateixeira** [comment]
As per the table in the other issues, we will:
1. Change the logical model so that nextInvitationIndication is a codeable concept
2. Create the value set (and code system) to include the currently known codes below
3. Add a new element .nextInvitationDate - optional, data type = date, which is the expected date for the new invitation.



<html>
<body>


Type | Template
-- | --
VOLGENDE_UITNODIGING | De volgende uitnodiging is voorzien rond %1$s.
DEFINITIEF_UITGESLOTEN | Je ontvangt geen volgende uitnodiging meer.
NIET_IN_DOELGROEP | Je ontvangt geen volgende uitnodiging. De leeftijdsgroep voor dit bevolkingsonderzoek start vanaf het jaar waarin je 50 jaar wordt en loopt tot en met het jaar waarin je 69 jaar wordt.
WEIGERING | Je ontvangt geen volgende uitnodiging omdat je hebt laten weten dat je geen uitnodiging meer wou ontvangen. Indien je meer informatie wenst over dit onderzoek kan je dit best bespreken met je arts.
TIJDELIJK_UITGESLOTEN | Volgens onze gegevens is dit onderzoek voor jou op dit moment niet nodig of niet aangewezen. Daarom ontvang je tijdelijk geen uitnodigingen meer. De volgende uitnodiging is voorzien rond %1$s. Indien je hierover meer wenst te weten, kan je dit bespreken met je arts.
ONDUIDELIJK | De datum van volgende uitnodiging is afhankelijk van de uitslag van het verdere onderzoek.
ONGEDEFINIEERD | We kunnen niet bepalen wanneer u de volgende keer zal uitgenodigd worden.


</body>
</html>

**Comment by bdc-ehealth** [comment]
WG: we need to update the logical model and modify the description of the field. We also need to add the next invitation date. We will create an extension for this.

**Comment by bdc-ehealth** [comment]
WG: the description will in English, the designations will be English, French, German, Dutch if needed. There will be a "displayTemplate" property attached to the code for each language.
